In [23]:
import numpy as np

In [24]:
# An array is a data structure that stores numbers in rows and columns (like matrices in math).
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [25]:
## Matrix (2D Array)
matrix = np.array([[1 ,2 , 3],
                   [4, 5, 6]])
print(matrix) ## A 2D NumPy array = Matrix in math.

[[1 2 3]
 [4 5 6]]


####  Array Properties

In [26]:
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype) # shape = rows × columns, ndim = number of dimensions.

(2, 3)
2
6
int64


In [27]:
## Array Creation Methods
np.zeros((3,3))
np.ones((2,2))
np.arange(1,10,2)
np.linspace(0,1,5)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [29]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
np.eye(3) # Identity Matrix = used in ML as the base for transformations.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# Dot Product
# Used to combine features and weights in ML:
# y = w.x = w1x1 + w2x2 + w3x3
x = np.array([1, 2, 3])
w = np.array([4, 5, 6])
dot = np.dot(x, w)
print(dot)

32


#### Array Operations

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


#### Matrix Operations

In [33]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print("Addition:\n", A + B)
print("Multiplication:\n", np.dot(A, B)) # Matrix multiplication = combines features and weights.
print("Transpose:\n", A.T) # Transpose = swaps rows ↔ columns.
print("Inverse:\n", np.linalg.inv(A)) #Inverse = used in solving linear equations (normal equation in Linear Regression).

Addition:
 [[3 2]
 [4 7]]
Multiplication:
 [[ 4  6]
 [10 12]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


####  Array Slicing & Indexing

In [34]:
# Slicing helps in feature selection in datasets.
arr = np.array([[10, 20, 30],
                [40, 50, 60], # Array Slicing & Indexing
                [70, 80, 90]])

print(arr[0, 1]) # 20
print(arr[:, 1])
print(arr[1, :])     # row 1 → [40, 50, 60]
print(arr[0:2, 1:3]) # submatrix

20
[20 50 80]
[40 50 60]
[[20 30]
 [50 60]]


In [35]:
import numpy as np

# Features (X): height, weight
X = np.array([[150, 60],
              [160, 65],
              [170, 72]])

# Weights (W): learned coefficients
W = np.array([0.5, 0.8])

# Predicted output (y)
y_pred = np.dot(X, W)
print("Predicted Output:", y_pred)

Predicted Output: [123.  132.  142.6]


In [40]:
# Standardization
data = np.array([32,67,43,87,85,34,67])
data_mean = np.mean(data)
data_std = np.std(data)
Standardization = (data - data_mean)/data_std

- Z-Score
-	Mean becomes 0
-	Standard deviation becomes 1
-	Values can be negative or >1
-	Used in ML algorithms & statistics
$$
Z = \frac{X - \mu}{\sigma}
$$

In [ ]:
print(Standardization)

[-1.27668549  0.36094773 -0.76200076  1.29673814  1.2031591  -1.18310645
  0.36094773]


- Normalization scales numeric features to 0–1 range to improve model accuracy and speed
- Normalization  formula
$$
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
$$

In [ ]:
data_min = np.min(data)
data_max = np.max(data)
normalization = (data-data_min)/(data_max-data_min)
## Result --> values become 0 and 1 

In [43]:
print(normalization)

[0.         0.63636364 0.2        1.         0.96363636 0.03636364
 0.63636364]


In [45]:
### Aggrate function
a = np.array([8,7,6,5,4,5,7,8])
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))

50
6.25
8
4
1.3919410907075054
